public class FB_ContractsController {
    
    private final Contract contractInstance;
    public FB_ContractsController(ApexPages.StandardController controller) 
    {
        this.contractInstance = (Contract)controller.getRecord();
    }
    public void addMachInfo()
    {
        
    }
    public void addETA()
    {
    }
    public void ConfirmDis2Ware()
    {
    }
    public void ConfirmDisp2Dist()
    {
    }
    

}